faiss_create_index_app:
  gensim_model:
    fname    : "/data/nlp/corpora/softrules/models/glove.6B.50d.txt"
    binary   : False
    no_header: True
  index_save_path: "/data/nlp/corpora/softrules/faiss_index/glove.6B.50d_index"
  vocab_save_path: "/data/nlp/corpora/softrules/faiss_index/glove.6B.50d_vocab"