word_average_eval:
  dataset_path: "/data/nlp/corpora/softrules/tacred/processed/dev.jsonl"
  rules_path  : "/data/nlp/corpora/softrules/tacred/processed/train_rules"
  thresholds: [0.5, 0.6, 0.7, 0.8, 0.9, 0.95, 0.99, 0.999]